# -----------------------------------------------
# Global Configuration
# -----------------------------------------------

# Default logger configuration
# Used as a base configuration for other loggers
defaultLogger: &defaultLogger
  # Log level settings
  level: "all"                        # Log level - captures all logs
  flags: 42                           # Log flags for formatting

  # Log file settings
  file: "{Y-m-d}.log"                 # Log filename format with date pattern
  rotateExpire: "7d"                  # Retain logs for 7 days
  rotateBackupLimit: 2                # Maximum number of backup files
  rotateBackupCompress: 2             # Compression level (0-9, higher = more compression)

  # Display settings
  stdoutColorDisabled: false          # Enable colored output in terminal
  writerColorEnable: false            # Disable color codes in log files

# -----------------------------------------------
# Database Configuration
# -----------------------------------------------
database:
  # Database logger configuration
  logger:
    path: "logs/database"             # Path for database log files
    stdout: true                      # Output logs to console
    <<: *defaultLogger                # Inherit settings from defaultLogger

  # Default database connection
  default:
    link: "mysql:username:password@tcp(127.0.0.1:3306)/fastkit?loc=Local&parseTime=true&charset=utf8mb4"
    debug: true                       # Enable SQL debugging
    prefix: "fk_"                     # Table prefix for all tables
